export const COMMON_CONSTS = {
	OVERVIEW_JOURNEY_ID: 'edit-case-overview',
	GATEWAY_1_JOURNEY_ID: 'gateway-1',
	GATEWAY_2_JOURNEY_ID: 'gateway-2',
	GATEWAY_3_JOURNEY_ID: 'gateway-3',
	EXAMINATION_JOURNEY_ID: 'examination',
	OVERVIEW: 'overview',
	ASSESSOR_GATEWAY_2_QUESTION: 'assessor-gateway-2',
	ASSESSOR_GATEWAY_3_QUESTION: 'assessor-gateway-3',
	PROGRAMME_OFFICER_QUESTION: 'programme-officer',
	CHECK_LPAS_QUESTION: 'check-lpas',
	CHECK_CONTACT_DETAILS_QUESTION: 'check-contact-details',
	EXAMINING_INSPECTOR_1_QUESTION: 'examining-inspector-1',
	EXAMINING_INSPECTOR_2_QUESTION: 'examining-inspector-2',
	EXAMINING_INSPECTOR_3_QUESTION: 'examining-inspector-3',
	EXAMINATION_WEBSITE_QUESTION: 'examination-website',
	QA_INSPECTOR_1_QUESTION: 'qa-inspector-1',
	QA_INSPECTOR_2_QUESTION: 'qa-inspector-2',
	QA_INSPECTOR_3_QUESTION: 'qa-inspector-3',
	SIGNED_SLA_QUESTION: 'signed-sla',
	GATEWAY_2_ASSESSOR_QUESTION: 'gateway-2-assessor',
	GATEWAY_2_REPORT_QUESTION: 'gateway-2-report',
	GATEWAY_2_REPORT_ISSUED_DATE_QUESTION: 'gateway-2-report-issued-date',
	GATEWAY_3_ASSESSOR_NAME_QUESTION: 'gateway-3-assessor-name',
	GATEWAY_3_DECISION_QUESTION: 'gateway-3-decision',
	GATEWAY_3_DOCUMENT_QUESTION: 'gateway-3-document',
	GATEWAY_3_REPORT_ISSUED_DATE_QUESTION: 'gateway-3-report-issued-date'
};
